---
- name: "2.2.1.4 Ensure systemd-timesyncd is configured (Scored)"
  block:
  - name: "2.2.1.4 Ensure systemd-timesyncd is configured"
    systemd:
      state: started
      enabled: yes      
      force: yes
      name: systemd-timesyncd.service
  - name: "2.2.1.4 Enable ntp"
    command: /usr/bin/timedatectl set-ntp true
  when: ansible_facts['service_mgr'] == "systemd"
  tags:
    - cis
    - cis.2
    - cis.2.2
    - cis.2.2.1
    - cis.2.2.1.4
    - scored

