---
- name: "2.3.4 Ensure telnet Client is not installed (Scored)"
  block:
  - name: "2.3.4 Check if telnet Client is installed"
    command: rpm -q netkit-telnet
    args:
      warn: no
    register: rpm_check
    failed_when: rpm_check.rc >= 2
  - name: "2.3.4 Uninstall NIS client"
    command: rpm -e netkit-telnet
    when: rpm_check.rc == 0  
  tags:
    - cis
    - cis.2
    - cis.2.3
    - cis.2.3.4
    - scored

