---
- name: Configure System Event Log (Application) | windows-audit-100
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\Application
    name: "MaxSize"
    data: "1"
    type: dword
  notify: Change Required

- name: Configure System Event Log (Security) | windows-audit-101
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\Security
    name: "MaxSize"
    data: "1"
    type: dword
  notify: Change Required

- name: Configure System Event Log (Setup) | windows-audit-102
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\Setup
    name: "MaxSize"
    data: "1"
    type: dword
  notify: Change Required

- name: Configure System Event Log (System) | windows-audit-103
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\System
    name: "MaxSize"
    data: "1"
    type: dword
  notify: Change Required

- name: Account Logon Audit Log | windows-audit-203
  win_command: AuditPol /Set /Category:"Account Logon" /Failure:Enable /Success:Enable
  register: accountLogonAudit
  args:
    creates: C:\accountLogonAudit.lock
  notify: Change Required

- name: Create accountLogonAudit.lock if account audit log was activated
  win_copy:
    dest: C:\accountLogonAudit.lock
    content: ""
    force: no
  when: accountLogonAudit
  notify: Change Required

- name: Audit Application Group Management | windows-audit-204
  win_command: AuditPol /Set /SubCategory:"Application Group Management" /Failure:Enable /Success:Enable
  register: appGroupMngmtAudit
  args:
    creates: C:\appGroupMngmtAudit.lock
  notify: Change Required

- name: Create appGroupMngmtAudit.lock if group manangement audit log was activated
  win_copy:
    dest: C:\appGroupMngmtAudit.lock
    content: ""
    force: no
  when: appGroupMngmtAudit
  notify: Change Required

- name: Audit Computer Account Management | windows-audit-205
  win_command: AuditPol /Set /SubCategory:"Computer Account Management" /Failure:Enable /Success:Enable
  register: appAccountMngmtAudit
  args:
    creates: C:\appAccountMngmtAudit.lock
  notify: Change Required

- name: Create appAccountMngmtAudit.lock if computer account manangement audit log was activated
  win_copy:
    dest: C:\appAccountMngmtAudit.lock
    content: ""
    force: no
  when: appAccountMngmtAudit
  notify: Change Required

- name: Audit Application Group Management | windows-audit-206
  win_command: AuditPol /Set /SubCategory:"Distribution Group Management" /Failure:Enable /Success:Enable
  register: distGroupMngmtAudit
  args:
    creates: C:\distGroupMngmtAudit.lock
  notify: Change Required

- name: Create distGroupMngmtAudit.lock if dist group manangement audit log was activated
  win_copy:
    dest: C:\distGroupMngmtAudit.lock
    content: ""
    force: no
  when: distGroupMngmtAudit
  notify: Change Required
...