---
- name: "1.7.1.6 Ensure permissions on /etc/issue.net are configured (Scored)"
  file:
      dest: /etc/issue.net
      owner: root
      group: root
      mode: 0644
  tags:
      - cis
      - cis.1
      - cis.1.7
      - cis.1.7.1
      - cis.1.7.1.6
      - scored
