---
- name: "1.7.1.5 Ensure permissions on /etc/issue are configured (Scored)"
  file:
      dest: /etc/issue
      owner: root
      group: root
      mode: 0644
  tags:
      - cis
      - cis.1
      - cis.1.7
      - cis.1.7.1
      - cis.1.7.1.5
      - scored
