---
# proxy environments
proxy_env: http:/plproxy.pacificlife.net:8080

#snow_record variables
sn_username: Prod.SplunkRest@pacificlife.com
sn_password: !vault

sn_instance: paclifedev

#data variables
sn_severity: 3
sn_priority: 3