---
- name: yum update servers (no reboots)
  hosts: platform_linux
  any_errors_fatal: false

  tasks:
  - name: Referring to rhel_patch role
    include_role: 
      name: rhel_patch
      tasks_from: yum_update
...