---
- name: Get all the Systems OSs
  hosts: platform_linux
  remote_user: ansible.linux
  gather_facts: yes
  become: false

  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }} {{ ansible_distribution_version}}"
...
  