---
- hosts: localhost
  connection: local
  environment: "{{ pl_proxy }}"

  tasks:
  - name: Include servicenow role
    include_role: 
      name: servicenow
      tasks_from: find_ticket
    vars:
      username: "{{ pl_snow_username }}"
      password: "{{ pl_snow_password }}"
      instance: "{{ pl_snow_instance }}"
...