---
- name: ServiceNow - Create Ticket
  hosts: localhost
  connection: local
  environment: "{{ pl_proxy }}"

  tasks:
  - name: Include servicenow role and create_ticket task
    include_role: 
      name: servicenow
      tasks_from: create_ticket
    vars:
      sn_username: "{{ pl_snow_username }}"
      sn_password: "{{ pl_snow_password }}"
      sn_instance: "{{ pl_snow_instance }}"
...