---
# roles:
  # Install a role from Ansible Galaxy.
  # - name: geerlingguy.java
  #   version: 1.9.6

collections:
# https://github.com/ansible-collections/amazon.aws
- name: amazon.aws
  version: 1.2.1