---
- name: "6.1.11 Ensure no unowned files or directories exist (Scored)"
  shell: |
     entry=''
     file_list=''
     file_list="$(df -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nouser)"
     for entry in $file_list; do
       chown root "$entry"
     done
  tags:
      - cis
      - cis.6
      - cis.6.1
      - cis.6.1.11
      - scored
