---
- name: "6.2.11 Ensure no users have .forward files (Scored)"
  shell: |
    grep -E -v '^(root|halt|sync|shutdown)' /etc/passwd | \
      awk -F: '($7 != "'"/usr/sbin/nologin"'" && $7 != "/bin/false") { print $1 " " $6 }' | \
      while read user dir; do
        [ -d "$dir" -a ! -h "$dir/.forward" -a -f "$dir/.forward" ] && rm -f "$dir/.forward"
      done
  register: result
  failed_when: result.rc != 1
  tags:
    - cis
    - cis.6
    - cis.6.2
    - cis.6.2.11
    - scored

