---
- name: "4.1.5 Ensure events that modify date and time information are collected (Scored)"
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    create: yes
    marker: "# {mark} of CIS-4.1.5"
    block: |
      -a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change
      -a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change
      -a always,exit -F arch=b64 -S clock_settime -k time-change
      -a always,exit -F arch=b32 -S clock_settime -k time-change
      -w /etc/localtime -p wa -k time-change
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.5
      - scored
