---
- name: "4.1.1.3 Ensure audit logs are not automatically deleted (Scored)"
  vars:
    file_authd_config: /etc/audit/auditd.conf
  block:
    - name: "4.1.1.3 Ensure audit logs are not automatically deleted"
      lineinfile:
        path: "{{ file_authd_config }}"
        regexp: '^[#\\s]*max_log_file_action\\s+=.*$'
        line: "max_log_file_action = keep_logs"
        state: present

  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.1
      - cis.4.1.1.3
      - scored
