---
- name: "4.1.19 Ensure the audit configuration is immutable (Scored)"
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    create: no
    insertafter: EOF
    regexp: "^-e 2"
    line: "-e 2"
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.19
      - scored
