---
- name: "4.1.13 Ensure use of privileged commands is collected (Scored)"
  vars:
    audit_rules: /etc/audit/rules.d/audit.rules
  shell: |
    echo "# BEGIN of CIS-4.1.13" >> "{{ audit_rules }}"
    find / -xdev \( -perm -4000 -o -perm -2000 \) -type f | \
      awk '{print "-a always,exit -F path=" $1 " -F perm=x -F auid>=500 -F auid!=-1 -k privileged" }' >> \
        "{{ audit_rules }}"
    echo "# END of CIS-4.1.13" >> "{{ audit_rules }}"
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.13
      - scored
