---
- name: "4.1.18 Ensure kernel module loading and unloading is collected (Scored)"
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    create: no
    insertafter: EOF
    marker: "# {mark} of CIS-4.1.18"
    block: |
      -w /sbin/insmod -p x -k modules
      -w /sbin/rmmod -p x -k modules
      -w /sbin/modprobe -p x -k modules
      -a always,exit -F arch=b64 -S init_module -S delete_module -k modules
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.18
      - scored
