---
- name: Installing Applications Updates
  win_updates:
    category_names: Application
    reboot: no
    state: installed
  tags:
  - Application

- name: Installing Security Updates
  win_updates:
    category_names: SecurityUpdates
    reboot: no
    state: installed
  tags:
  - SecurityUpdates

- name: Installing Critical Updates
  win_updates:
    category_names: CriticalUpdates
    reboot: no
    state: installed
  tags:
  - CriticalUpdates

- name: Installing Rollup Updates
  win_updates:
    category__names: UpdateRollups
    reboot: no
    state: installed
  tags:
  - UpdateRollups

- name: Installing ServicePacks Updates
  win_updates:
      category_names: ServicePacks 
      reboot: no 
      state: installed 
  tags:
  - ServicePacks
  
- name: Installing Connectors Updates
  win_updates:
      category_names: Connectors 
      reboot: no 
      state: installed 
  tags:
  - Connectors
  
- name: Installing DefinitionUpdates Updates
  win_updates:
      category_names: DefinitionUpdates 
      reboot: no 
      state: installed 
  tags:
  - DefinitionUpdates
  
- name: Installing DeveloperKits Updates
  win_updates:
      category_names: DeveloperKits 
      reboot: no 
      state: installed 
  tags:
  - DeveloperKits
  
- name: Installing FeaturePacks Updates
  win_updates:
      category_names: ServicePacks 
      reboot: no 
      state: installed 
  tags:
  - FeaturePacks
  
- name: Installing DeveloperKits Updates
  win_updates:
      category_names: DeveloperKits 
      reboot: no 
      state: installed 
  tags:
  - DeveloperKits
  
- name: Installing FeaturePacks Updates
  win_updates:
      category_names: FeaturePacks 
      reboot: no 
      state: installed 
  tags:
  - FeaturePacks
  
- name: Installing Guidance Updates
  win_updates:
      category_names: Guidance 
      reboot: no 
      state: installed 
  tags:
  - Guidance

- name: Installing Tools
  win_updates:
      category_names: Tools 
      reboot: no 
      state: installed 
  tags:
  - Tools

- name: Installing Updates
  win_updates:
      category_names: Updates 
      reboot: no 
      state: installed 
  tags:
  - Updates

- name: Search and download any patches without installing them
  win_updates:
    state: downloaded
...