---
- name: "4.1.14 Verify that successful file system mounts are collected (Scored)"
  vars:
    audit_rules: /etc/audit/rules.d/audit.rules
  shell: |
      grep -q '^-a always,exit -F arch=b64 -S mount -F auid>=500 -F auid!=4294967295 -k mounts$' {{ audit_rules }} && \
      grep -q '^-a always,exit -F arch=b32 -S mount -F auid>=500 -F auid!=4294967295 -k mounts$' {{ audit_rules }}
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.14
      - scored
