---
- name: "4.1.13 Verify that use of privileged commands is collected (Scored)"
  shell: |
    if [ $(find / -xdev \( -perm -4000 -o -perm -2000 \) -type f | wc -l) -gt 0 ]; then
      grep -q '^-a.*privileged$' /etc/audit/rules.d/audit.rules
    fi
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.13
      - scored
