---
- name: "4.1.11 Verify that discretionary access control permission modification events are collected (Scored)"
  vars:
    audit_rules: /etc/audit/rules.d/audit.rules
  shell: |
      grep -q '^-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>=500 -F auid!=4294967295 -k perm_mod$' {{ audit_rules }} && \
      grep -q '^-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=500 -F auid!=4294967295 -k perm_mod$' {{ audit_rules }} && \
      grep -q '^-a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>=500 -F auid!=4294967295 -k perm_mod$' {{ audit_rules }} && \
      grep -q '^-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>=500 -F auid!=4294967295 -k perm_mod$' {{ audit_rules }} && \
      grep -q '^-a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=500 -F auid!=4294967295 -k perm_mod$' {{ audit_rules }} && \
      grep -q '^-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=500 -F auid!=4294967295 -k perm_mod$' {{ audit_rules }}
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.11
      - scored
