---
- name: "4.1.6 Verify that events that modify date and time information are collected (Scored)"
  vars:
    audit_rules: /etc/audit/rules.d/audit.rules
  shell: |
      grep -q -- "-w /etc/group -p wa -k identity" {{ audit_rules }} && \
      grep -q -- "-w /etc/passwd -p wa -k identity" {{ audit_rules }} &&\
      grep -q -- "-w /etc/gshadow -p wa -k identity" {{ audit_rules }} && \
      grep -q -- "-w /etc/shadow -p wa -k identity" {{ audit_rules }} && \
      grep -q -- "-w /etc/security/opasswd -p wa -k identity" {{ audit_rules }}

  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.6
      - scored
