---
- name: "4.1.1.2 Verify that system is disabled when audit logs are full (Scored)"
  vars:
    file_authd_config: /etc/audit/auditd.conf
  shell: |
    grep -q '^space_left_action = email$' {{ file_authd_config }} && \
    grep -q '^action_mail_acct = root$' {{ file_authd_config }} && \
    grep -q '^admin_space_left_action = halt$' {{ file_authd_config }}
      
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.1
      - cis.4.1.1.2
      - scored
