---
- name: "4.1.15 Verify that file deletion events by users are collected (Scored)"
  vars:
    audit_rules: /etc/audit/rules.d/audit.rules
  shell: |
      grep -q '^-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=500 -F auid!=4294967295 -k delete$' {{ audit_rules }} && \
      grep -q '^-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=500 -F auid!=4294967295 -k delete$' {{ audit_rules }}
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.15
      - scored
