---
- name: "4.1.7 Verify that vents that modify the system's network environment are collected (Scored)"
  vars:
    audit_rules: /etc/audit/rules.d/audit.rules
  shell: |
      grep -q '^-a always,exit -F arch=b64 -S sethostname -S setdomainname -k system-locale$' {{ audit_rules }} && \
      grep -q '^-a always,exit -F arch=b32 -S sethostname -S setdomainname -k system-locale$' {{ audit_rules }} &&\
      grep -q '^-w /etc/issue -p wa -k system-locale$' {{ audit_rules }} && \
      grep -q '^-w /etc/issue.net -p wa -k system-locale$' {{ audit_rules }} && \
      grep -q '^-w /etc/hosts -p wa -k system-locale$' {{ audit_rules }} && \
      grep -q '^-w /etc/sysconfig/network -p wa -k system-locale$' {{ audit_rules }}

  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.7
      - scored
