---
- name: "2.3.5 Verify that LDAP Client is not installed (Scored)"
  block:
   - name: "2.3.5 Verify that LDAP Client is not installed"
     command: rpm -q openldap-clients
     args:
       warn: no
     register: rpm_check
     failed_when: rpm_check.rc >= 2
   - fail:
       msg: "2.3.5 Failed: LDAP Client is installed"
     when: rpm_check.rc == 0
  tags:
    - cis
    - cis.2
    - cis.2.3
    - cis.2.3.5
    - scored

