---
- name: Create a incident ticket
  snow_record:
    username: "{{ sn_username }}"
    password: "{{ sn_password }}"
    instance: "{{ sn_instance }}"
    state: present
    table: incident
    # Default: table is incident for type of ticket
    # Change to "change", etc. if you want another type 
    data:
#      assignment_group: "{{ sn_assignment_group }}"
#      caller: "{{ sn_caller }}"
#      contact: "{{ sn_contact }}"
#      category: "{{ sn_category }}"
#      contact_type: "{{ sn_contact_type }}"
      severity: "{{ sn_severity }}"
      priority: "{{ sn_priority }}"
#      impact: "{{ sn_impact }}"
#      urgency: "{{ sn_urgency }}"
      short_description: "Test incident opened by Ansible {{ ansible_date_time.iso8601 }}"
...