---
- name: Create a incident
  snow_record:
    state: present
    table: incident
    username: "{{ sn_username }}"
    password: "{{ sn_password }}"
    instance: "{{ sn_instance }}"
    data:
      severity: "{{ sn_severity }}"
      priority: "{{ sn_priority }}"
      short_description: "This is a test opened by Ansible {{ ansible_date_time.iso8601 }}"
...