---
- name: Create a incident
  snow_record:
    username: "{{ sn_username }}"
    password: "{{ sn_password }}"
    instance: "{{ sn_instance }}"
    state: present
    data:
      short_description: "This is a test opened by Ansible {{ ansible_date_time.iso8601 }}"
      severity: "{{ sn_severity }}"
      priority: "{{ sn_priority }}"
...