---
- name: Grab a user record
  snow_record_find:
    username: "{{ sn_username }}"
    password: "{{ sn_password }}"
    instance: "{{ sn_instance }}"
    state: present
    table: sys_user
    lookup_field: sys_id
...