---
- name: Search for incident assigned to group, return specific fields
  snow_record_find:
    username: "{{ sn_username }}"
    password: "{{ sn_password }}"
    instance: "{{ sn_instance }}"
    table: incident
    query:
      assignment_group: f32ae02b1be10cd0532d6288bd4bcb13
    return_fields:
    - number
    - opened_at
    - short_description
...