---
- name: "6.1.9 Ensure permissions on /etc/gshadow- are configured (Scored)"
  file:
      dest: /etc/gshadow-
      state: touch
      owner: root
      group: root
      mode: 0600
  tags:
      - cis
      - cis.6
      - cis.6.1
      - cis.6.1.9
      - scored
