---
- name: "6.1.6 Ensure permissions on /etc/passwd- are configured (Scored)"
  file:
      dest: /etc/passwd-
      owner: root
      group: root
      mode: 0600
  tags:
      - cis
      - cis.6
      - cis.6.1
      - cis.6.1.6
      - scored
