---
- name: "6.2.3 Ensure no legacy + entries exist in /etc/shadow (Scored)"
  vars:
    file: /etc/shadow
  lineinfile:
    path: "{{ file }}"
    state: absent 
    regexp: '^\+:'
  tags:
    - cis
    - cis.6
    - cis.6.2
    - cis.6.2.3
    - scored

