---
- name: "6.2.5 Ensure root is the only UID 0 account (Scored)"
  shell: |
    usr=''
    for usr in $(awk -F: '($3 == 0) { print $1 }' /etc/passwd); do
      [ "$usr" != "root" ] && userdel -Z -r -f "$usr"
    done
  register: result
  failed_when: result.rc != 1
  tags:
    - cis
    - cis.6
    - cis.6.2
    - cis.6.2.5
    - scored

