---
- name: "6.2.4 Ensure no legacy + entries exist in /etc/group (Scored)"
  vars:
    file: /etc/group
  lineinfile:
    path: "{{ file }}"
    state: absent 
    regexp: '^\+:'
  tags:
    - cis
    - cis.6
    - cis.6.2
    - cis.6.2.4
    - scored

