---
- name: "1.6.1 Ensure SELinux or AppArmor are installed (Scored)"
  block:
   - name: "1.6.1 Check if AppArmor is installed"
     command: rpm -q libapparmor
     args:
       warn: no
     register: apparmor_rpm_check
     failed_when: apparmor_rpm_check.rc >= 2
   - name: "1.6.1 Check if Selinux is installed"
     command: rpm -q libselinux
     args:
       warn: no
     register: selinux_rpm_check
     failed_when: selinux_rpm_check.rc >= 2
   - name: "1.6.1 Install apparmor or selinux"
     block:
     - name: "1.6.1 Try to install Apparmor"
       shell: tdnf install libapparmor -y
       register: output_1
     - name: "1.6.1 Try to install Selinux"
       shell: tdnf install libselinux -y
       when: output_1.rc != 0
     when: apparmor_rpm_check.rc != 0 and selinux_rpm_check.rc != 0

  tags:
    - cis
    - cis.1
    - cis.1.6
    - cis.1.6.1
    - scored

