---
- name: "5.2.9 Ensure SSH PermitEmptyPasswords is disabled (Scored)"
  vars:
    file: /etc/ssh/sshd_config
  lineinfile:
    path: "{{ file }}"
    regexp: "^#PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"
  tags:
      - cis
      - cis.5
      - cis.5.2
      - cis.5.2.9
      - scored
