---
- name: "5.2.12 Ensure only approved MAC algorithms are used (Scored)"
  vars:
    file: /etc/ssh/sshd_config
  lineinfile:
    path: "{{ file }}"
    line: "{{ my_result.line }}"
  with_items:
    - { line: "# MAC algorithms"} 
    - { line: "MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"} 
  loop_control:
    loop_var: my_result
  tags:
      - cis
      - cis.5
      - cis.5.2
      - cis.5.2.12
      - scored
