---
- name: "5.2.4 Ensure SSH X11 forwarding is disabled (Scored)"
  vars:
    file: /etc/ssh/sshd_config
  lineinfile:
    path: "{{ file }}"
    regexp: "^#X11Forwarding"
    line: "X11Forwarding no"
  tags:
      - cis
      - cis.5
      - cis.5.2
      - cis.5.2.4
      - scored
