---
- name: "5.2.7 Ensure SSH HostbasedAuthentication is disabled (Scored)"
  vars:
    file: /etc/ssh/sshd_config
  lineinfile:
    path: "{{ file }}"
    regexp: '^#HostbasedAuthentication'
    line: "HostbasedAuthentication no"
  tags:
      - cis
      - cis.5
      - cis.5.2
      - cis.5.2.7
      - scored
