---
- name: "5.2.3 Ensure SSH LogLevel is set to INFO (Scored)"
  vars:
    file: /etc/ssh/sshd_config
  lineinfile:
    path: "{{ file }}"
    regexp: '^#LogLevel'
    line: "LogLevel INFO"
  tags:
      - cis
      - cis.5
      - cis.5.2
      - cis.5.2.3
      - scored
