---
- name: "5.4.1.3 Ensure password expiration warning days is 7 or more (Scored)"
  vars:
    file: /etc/login.defs
    pass_warning_days: 7
  block:
    - name: "5.4.1.3 - Obtain a list of user accounts"
      shell: "egrep ^[^:]+:[^\\!*] /etc/shadow | cut -d: -f1"
      register: egrep_5_4_1_3
      check_mode: no
      changed_when: False
    - name: "5.4.1.3 - Ensure password expiration warning days is 7 or more"
      lineinfile:
        path: "{{ file }}"
        regexp: "^PASS_WARN_AGE\\s+"
        line: "PASS_WARN_AGE {{ pass_warning_days }}"
    - name: "5.4.1.3 - Set password expiration warning days."
      command: "chage --mindays {{ pass_warning_days }} {{ my_result }}"
      with_items: "{{ egrep_5_4_1_3.stdout_lines }}"
      loop_control:
        loop_var: my_result
  tags:
      - cis
      - cis.5
      - cis.5.4
      - cis.5.4.1
      - cis.5.4.1.3
      - scored
