---
- name: "3.6.3 Ensure loopback traffic is configured (Scored)"
  block:
    - name: 3.6.3 Configure INPUT loopback with source 0.0.0.0/0
      iptables:
        chain: INPUT
        in_interface: "lo"
        jump: ACCEPT
      become: yes
    - name: 3.6.3 Configure OUTPUT loopback with source 0.0.0.0/0
      iptables:
        chain: OUTPUT
        out_interface: "lo"
        jump: ACCEPT
      become: yes
    - name: 3.6.3 Configure INPUT loopback with source 127.0.0.0/8
      iptables:
        chain: INPUT
        source: 127.0.0.0/8
        jump: DROP
      become: yes
  tags:
    - cis
    - cis.3
    - cis.3.6
    - cis.3.6.3
    - scored

