---
- name: "3.6.4 Ensure outbound and established connections are configured (Not Scored)"
  block:
    - name: 3.6.4 Configure outbound, established connections for OUTPUT for TCP protocol
      iptables:
        chain: OUTPUT
        protocol: tcp
        match: state
        ctstate: ESTABLISHED,NEW
        jump: ACCEPT
      become: yes
    - name: 3.6.4 Configure outbound, established connections for OUTPUT for UDP protocol
      iptables:
        chain: OUTPUT
        protocol: udp
        match: state
        ctstate: ESTABLISHED,NEW
        jump: ACCEPT
      become: yes
    - name: 3.6.4 Configure outbound, established connections for OUTPUT for icmp protocol
      iptables:
        chain: OUTPUT
        protocol: icmp
        match: state
        ctstate: ESTABLISHED,NEW
        jump: ACCEPT
      become: yes
    - name: 3.6.4 Configure outbound, established connections for INPUT for tcp protocol
      iptables:
        chain: INPUT
        protocol: tcp
        match: state
        ctstate: ESTABLISHED
        jump: ACCEPT
      become: yes
    - name: 3.6.4 Configure outbound, established connections for INPUT for udp protocol
      iptables:
        chain: INPUT
        protocol: udp
        match: state
        ctstate: ESTABLISHED
        jump: ACCEPT
      become: yes
    - name: 3.6.4 Configure outbound, established connections for INPUT for icmp protocol
      iptables:
        chain: INPUT
        protocol: icmp
        match: state
        ctstate: ESTABLISHED
        jump: ACCEPT
      become: yes
  tags:
    - cis
    - cis.3
    - cis.3.6
    - cis.3.6.4
    - notscored

