---
- name: "5.1.5 Verify permissions on /etc/cron.weekly are configured (Scored)"
  block:
    - name: "5.1.5 verify permissions"
      stat:
        path: /etc/cron.weekly
      register: etc_cron_weekly_result
    - fail:
        msg: "5.1.5 failed to verify uid. expected: 0. found: {{ etc_cron_weekly_result.stat.uid }}"
      when: etc_cron_weekly_result.stat.uid != 0
    - fail:
        msg: "5.1.5 failed to verify gid. expected: 0. found: {{ etc_cron_weekly_result.stat.gid }}"
      when: etc_cron_weekly_result.stat.gid != 0
    - fail:
        msg: "5.1.5 failed to verify permissions. expected: 0600. found: {{ etc_cron_weekly_result.stat.mode }}"
      when: etc_cron_weekly_result.stat.mode != "0600"
  tags:
    - cis
    - cis.5
    - cis.5.1
    - cis.5.1.5
    - scored

