---
- name: "5.2.8 Verify SSH root login is disabled (Scored)"
  vars:
    file: /etc/ssh/sshd_config
  block:
    - name: "5.2.8 Verify SSH root login is disabled"
      lineinfile:
        path: "{{ file }}"
        line: "PermitRootLogin no"
        state: present
      check_mode: yes
      register: presence
    - fail:
        msg: "5.2.8 failed to Verify SSH root login is disabled. Expected: Entries PermitRootLogin no in the file {{ file }}"
      when: presence is changed
  tags:
    - cis
    - cis.5
    - cis.5.2
    - cis.5.2.8
    - scored

