---
- name: "5.2.3 Verify SSH LogLevel is set to INFO (Scored)"
  vars:
    file: /etc/ssh/sshd_config
  block:
    - name: "5.2.3 Verify SSH LogLevel is set to INFO"
      lineinfile:
        path: "{{ file }}"
        line: "LogLevel INFO"
        state: present
      check_mode: yes
      register: presence
    - fail:
        msg: "5.2.3 failed to Verify SSH LogLevel is set to INFO. Expected: Entries LogLevel INFO in the file {{ file }}"
      when: presence is changed
  tags:
    - cis
    - cis.5
    - cis.5.2
    - cis.5.2.3
    - scored

