---
- name: "5.2.5 Verify SSH MaxAuthTries is set to 4 or less (Scored)"
  vars:
    file: /etc/ssh/sshd_config
  block:
    - name: "5.2.5 Verify SSH MaxAuthTries is set to 2"
      lineinfile:
        path: "{{ file }}"
        line: "MaxAuthTries 2"
        state: present
      check_mode: yes
      register: presence
    - fail:
        msg: "5.2.4 failed to Verify SSH MaxAuthTries is set to 4 or less. Expected: Entries MaxAuthTries 2 in the file {{ file }}"
      when: presence is changed
  tags:
    - cis
    - cis.5
    - cis.5.2
    - cis.5.2.5
    - scored

