---
- name: "5.2.6 Verify SSH IgnoreRhosts is enabled (Scored)"
  vars:
    file: /etc/ssh/sshd_config
  block:
    - name: "5.2.6 Verify SSH IgnoreRhosts is enabled"
      lineinfile:
        path: "{{ file }}"
        line: "IgnoreRhosts yes"
        state: present
      check_mode: yes
      register: presence
    - fail:
        msg: "5.2.6 failed to Verify SSH IgnoreRhosts is enabled. Expected: Entries, IgnoreRhosts yes, in the file {{ file }}"
      when: presence is changed
  tags:
    - cis
    - cis.5
    - cis.5.2
    - cis.5.2.6
    - scored

