---
- name: "1.1.4 Verify if nosuid option set on /tmp partition (Scored)"
  block:
    - name: "1.1.4 Mount /proc"
      mount:
        path: /proc
        src: none
        fstype: proc
        state: mounted
    - name: "1.1.4 verify if nosuid option set on /tmp partition"
      shell: cat /proc/mounts | grep '\s/tmp\s' | grep  nosuid
      args:
        warn: no
      register: output_1
    - fail:
        msg: "1.1.4 failed to verify if nosuid option set on /tmp partition"
      when: output_1.rc != 0
  tags:
    - cis
    - cis.1
    - cis.1.1
    - cis.1.1.4
    - scored
