---
- name: "1.1.1 Verify if unused filesystems are disabled (Scored)"
  block:
    - name: "1.1.1.1 verify if cramfs filesystem is disabled"
      command: modprobe -n -v cramfs
      register: output_1
    - fail:
        msg: "1.1.1.1 cramfs filesystem is not disabled"
      when: output_1.stdout != "install /bin/true "
    - name: "1.1.1.2 verify if freevxfs filesystem is disabled"
      command: modprobe -n -v freevxfs
      register: output_2
    - fail:
        msg: "1.1.1.2 freevxfs filesystem is not disabled"
      when: output_2.stdout != "install /bin/true "
    - name: "1.1.1.3 verify if jffs2 filesystem is disabled"
      command: modprobe -n -v jffs2
      register: output_3
    - fail:
        msg: "1.1.1.3 jffs2 filesystem is not disabled"
      when: output_3.stdout != "install /bin/true "
    - name: "1.1.1.4 verify if hfs filesystem is disabled"
      command: modprobe -n -v hfs
      register: output_4
    - fail:
        msg: "1.1.1.4 hfs filesystem is not disabled"
      when: output_4.stdout != "install /bin/true "
    - name: "1.1.1.5 verify if hfsplus filesystem is disabled"
      command: modprobe -n -v hfsplus
      register: output_5
    - fail:
        msg: "1.1.1.5 hfsplus filesystem is not disabled"
      when: output_5.stdout != "install /bin/true "
    - name: "1.1.1.6 verify if squashfs filesystem is disabled"
      command: modprobe -n -v squashfs
      register: output_6
    - fail:
        msg: "1.1.1.6 squashfs filesystem is not disabled"
      when: output_6.stdout != "install /bin/true "
    - name: "1.1.1.7 verify if udf filesystem is disabled"
      command: modprobe -n -v udf
      register: output_7
    - fail:
        msg: "1.1.1.7 udf filesystem is not disabled"
      when: output_7.stdout != "install /bin/true "
    - name: "1.1.1.8 verify if vfat filesystem is disabled"
      command: modprobe -n -v vfat
      register: output_8
    - fail:
        msg: "1.1.1.8 vfat filesystem is not disabled"
      when: output_8.stdout != "install /bin/true "
  tags:
    - cis
    - cis.1
    - cis.1.1
    - cis.1.1.1
    - scored
