---
- name: "1.1.2 Verify if /tmp is configured (Scored)"
  block:
    - name: "1.1.2 Mount /proc"
      mount:
        path: /proc
        src: none
        fstype: proc
        state: mounted
    - name: "1.1.2 verify if /tmp is mounted"
      shell: cat /proc/mounts | grep '\s/tmp\s' 
      args:
        warn: no
      register: output_1
    - name: "1.1.2 verify that tmpfs has been mounted to /tmp"
      shell: grep -E '\s/tmp\s' /etc/fstab | grep -E -v '^\s*#'
      register: output_2
    - name: "1.1.2 verify that a system partition has been created for /tmp"
      command: systemctl is-enabled tmp.mount
      register: output_3
    - fail:
        msg: "1.1.2 failed to verify if /tmp is configured"
      when: output_1.rc != 0 and output_2.rc != 0 and (output_3.stdout != "generated " and output_3.rc != "enabled " )
  tags:
    - cis
    - cis.1
    - cis.1.1
    - cis.1.1.2
    - scored
