---
- name: "4.1.16 Ensure changes to system administration scope (sudoers) is collected (Scored)"
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    create: no
    insertafter: EOF
    marker: "# {mark} of CIS-4.1.16"
    block: |
      -w /etc/sudoers -p wa -k scope
      -w /etc/sudoers.d/ -p wa -k scope
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.16
      - scored
