---
- name: "4.1.8 Ensure events that modify the system's Mandatory Access Controls are collected (Scored)"
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    create: no
    insertafter: EOF
    marker: "# {mark} of CIS-4.1.8"
    block: |
      -w /etc/selinux/ -p wa -k MAC-policy
      -w /usr/share/selinux/ -p wa -k MAC-policy
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.8
      - scored
