---
- name: "4.1.10 Ensure session initiation information is collected (Scored)"
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    create: no
    insertafter: EOF
    marker: "# {mark} of CIS-4.1.10"
    block: |
      -w /var/run/utmp -p wa -k session
      -w /var/log/wtmp -p wa -k logins
      -w /var/log/btmp -p wa -k logins
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.10
      - scored
