---
- name: "4.1.14 Ensure successful file system mounts are collected (Scored)"
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    create: no
    insertafter: EOF
    marker: "# {mark} of CIS-4.1.14"
    block: |
      -a always,exit -F arch=b64 -S mount -F auid>=500 -F auid!=4294967295 -k mounts
      -a always,exit -F arch=b32 -S mount -F auid>=500 -F auid!=4294967295 -k mounts
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.14
      - scored
