---
- name: "4.1.9 Ensure login and logout events are collected (Scored)"
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    create: no
    insertafter: EOF
    marker: "# {mark} of CIS-4.1.9"
    block: |
      -w /var/log/faillog -p wa -k logins
      -w /var/log/lastlog -p wa -k logins
      -w /var/log/tallylog -p wa -k logins
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.9
      - scored
