---
- name: "4.2.2.3 Ensure journald is configured to write logfiles to persistent disk (Scored)"
  vars:
    journald_conf: /etc/systemd/journald.conf
  block:
    - name: "4.2.2.3 Ensure journald is configured to write logfiles to persistent disk"
      lineinfile:
        path: "{{ journald_conf }}"
        regexp: '^[#\\s]*Storage\\s*=.*$'
        line: "Storage=persistent"
        state: present

  tags:
      - cis
      - cis.4
      - cis.4.2
      - cis.4.2.2
      - cis.4.2.2.3
      - scored
