---
- name: "4.2.2.1 Ensure journald is configured to send logs to rsyslog (Scored)"
  vars:
    journald_conf: /etc/systemd/journald.conf
  block:
    - name: "4.2.2.1 Ensure journald is configured to send logs to rsyslog"
      lineinfile:
        path: "{{ journald_conf }}"
        regexp: '^[#\\s]*ForwardToSyslog\\s*=.*$'
        line: "ForwardToSyslog=yes"
        state: present

  tags:
      - cis
      - cis.4
      - cis.4.2
      - cis.4.2.2
      - cis.4.2.2.1
      - scored
