---
- name: "5.1.3 Ensure permissions on /etc/cron.hourly are configured (Scored)"
  file:
    path: "/etc/cron.hourly"
    owner: root
    group: root
    mode: 0600
  tags:
      - cis
      - cis.5
      - cis.5.1
      - cis.5.1.3
      - scored
