---
- name: "5.2.8 Ensure SSH root login is disabled (Scored)"
  vars:
    file: /etc/ssh/sshd_config
  lineinfile:
    path: "{{ file }}"
    regexp: "^PermitRootLogin no"
    line: "PermitRootLogin no"
  tags:
      - cis
      - cis.5
      - cis.5.2
      - cis.5.2.8
      - scored
