---
- name: "5.2.14 Ensure SSH LoginGraceTime is set to one minute or less (Scored)."
  vars:
    file: /etc/ssh/sshd_config
  lineinfile:
    path: "{{ file }}"
    regexp: "^#LoginGraceTime 2m$"
    line: "LoginGraceTime 60"
  tags:
      - cis
      - cis.5
      - cis.5.2
      - cis.5.2.14
      - scored
