---
- name: "5.4.1.1 Ensure password expiration is 90 days or less (Scored)"
  vars:
    file: /etc/login.defs
    pass_max_days: 90
  block:
    - name: "5.4.1.1 - Obtain a list of user accounts"
      shell: "egrep ^[^:]+:[^\\!*] /etc/shadow | cut -d: -f1"
      register: egrep_5_4_1_1
      check_mode: no
      changed_when: False
    - name: "5.4.1.1 - Ensure password expiration is 90 days or less"
      lineinfile:
        path: "{{ file }}"
        regexp: "^PASS_MAX_DAYS\\s+"
        line: "PASS_MAX_DAYS {{ pass_max_days }}"
    - name: "5.4.1.1 - Set password expiration for all user accounts"
      command: "chage --maxdays {{ pass_max_days }} {{ my_result }}"
      with_items: "{{ egrep_5_4_1_1.stdout_lines }}"
      loop_control:
        loop_var: my_result
  tags:
      - cis
      - cis.5
      - cis.5.4
      - cis.5.4.1
      - cis.5.4.1.1
      - scored
