---
- name: Updating all packages
  yum:
    name: '*'
    state: latest
    use_backend: yum
  tags:
  - all

- name: Updating emacs
  yum: 
    name: emacs
    state:
    use_backend: yum
  tags:
  - emacs
...
