---
- name: "1.1.15 Verify if nodev option set on /dev/shm partition (Scored)"
  block:
    - name: "1.1.15 Mount /proc"
      mount:
        path: /proc
        src: none
        fstype: proc
        state: mounted
    - name: "1.1.15 verify if nodev option set on /dev/shm partition"
      shell: cat /proc/mounts | grep '\s/dev/shm\s' | grep  nodev
      args:
        warn: no
      register: output_1
    - fail:
        msg: "1.1.15 failed to verify if nodev option set on /dev/shm partition"
      when: output_1.rc != 0
  tags:
    - cis
    - cis.1
    - cis.1.1
    - cis.1.1.15
    - scored
