---
- name: "3.4.5 Ensure permissions on /etc/hosts.deny are configured (Scored)"
  file:
      dest: /etc/hosts.deny
      state: touch
      owner: root
      group: root
      mode: 0644
  tags:
      - cis
      - cis.3
      - cis.3.4
      - cis.3.4.5
      - scored

