---
- name: "3.6.5 Ensure firewall rules exist for all open ports (Scored)"
  block:
    - name: 3.6.5 Configure firewall rules for protocol TCP for port 22
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: '22'
        match: state
        ctstate: NEW
        jump: ACCEPT
      become: yes
  tags:
    - cis
    - cis.3
    - cis.3.6
    - cis.3.6.5
    - scored

