---
- name: "5.2.7 Verify SSH HostbasedAuthentication is disabled (Scored)"
  vars:
    file: /etc/ssh/sshd_config
  block:
    - name: "5.2.7 Verify SSH HostbasedAuthentication is disabled"
      lineinfile:
        path: "{{ file }}"
        line: "HostbasedAuthentication no"
        state: present
      check_mode: yes
      register: presence
    - fail:
        msg: "5.2.7 failed to Verify SSH HostbasedAuthentication is disabled. Expected: Entries, HostbasedAuthentication no, in the file {{ file }}"
      when: presence is changed
  tags:
    - cis
    - cis.5
    - cis.5.2
    - cis.5.2.7
    - scored

