---
- name: "5.2.2 Verify SSH Protocol is set to 2 (Scored)"
  vars:
    file: /etc/ssh/sshd_config
  block:
    - name: "5.2.2 Verify SSH Protocol is set to 2"
      lineinfile:
        path: "{{ file }}"
        line: "Protocol 2"
        state: present
      check_mode: yes
      register: presence
    - fail:
        msg: "5.2.2 failed to verify SSH Protocol is set to 2. Expected: Entries Protocol 2 in the file {{ file }}"
      when: presence is changed
  tags:
    - cis
    - cis.5
    - cis.5.2
    - cis.5.2.2
    - scored

