---
- name: "5.3.3 Verify password reuse is limited (Scored)"
  vars:
    file: /etc/pam.d/system-auth
  block:
    - name: "5.3.3 Verify password reuse is limited"
      lineinfile:
        path: "{{ file }}"
        line: "{{ my_result.line }}"
        state: present
      check_mode: yes
      with_items:
        - { line: "# Set password reuse limit" }
        - { line: "password sufficient pam_unix.so remember=5" }
      loop_control:
        loop_var: my_result
      register: presence
    - fail:
        msg: "5.3.3 failed to Verify password reuse limit"
      when: presence is changed
  tags:
    - cis
    - cis.5
    - cis.5.3
    - cis.5.3.3
    - scored

