---
- name: "5.4.1.3 Verify password expiration warning days is 7 or more (Scored)"
  vars:
    file: /etc/login.defs
    pass_warning_days: 7
  block:
    - name: "5.4.1.3 Verify password expiration warning days is 7 or more."
      lineinfile:
        path: "{{ file }}"
        line: "PASS_WARN_AGE {{ pass_warning_days }}"
        state: present
      check_mode: yes
      register: presence
    - fail:
        msg: "5.4.1.3 Failed to Verify password expiration warning days."
      when: presence is changed
  tags:
    - cis
    - cis.5
    - cis.5.4
    - cis.5.4.1
    - cis.5.4.1.3
    - scored

