---
- name: "5.5 Verify root login is restricted to system console (Not Scored)"
  vars:
    file_securetty: /etc/securetty
  block:
    - name: "5.5 Verify root login is restricted to system console"
      stat:
        path: "{{ file_securetty }}"
      register: stat_result
    - fail:
        msg: "5.5 failed to verify root login is restricted to system console"
      when: stat_result.stat.exists == True
  tags:
      - cis
      - cis.5
      - cis.5.5
      - notscored
