---
- name: "6.2.2 Verify if no legacy + entries exist in /etc/passwd (Scored)"
  vars:
    file: /etc/passwd
  block:
    - name: 6.2.2 Verify if no legacy + entries exist in /etc/passwd
      lineinfile:
        path: "{{ file }}"
        line: "+:"
        state: present
      check_mode: yes
      register: presence
    - fail:
        msg: 6.2.2 failed to verify if no legacy + entries exist, legacy + entries are present in {{ file }}
      when: presence is not changed
  tags:
    - cis
    - cis.6
    - cis.6.2
    - cis.6.2.2
    - scored

