---
- name: |
    Control-ID:1.3
    Title: (L1) Ensure no unauthorized kernel modules are loaded on the host
    Description: ESXi hosts by default do not permit the loading of kernel modules that lack valid digital signatures. This feature can be overridden, which would allow unauthorized kernel modules to be loaded.
    Rationale: VMware provides digital signatures for kernel modules. Untested or malicious kernel modules loaded on the ESXi host can put the host at risk for instability and/or exploitation.
  shell: esxcli system module list
  notify: Change Required
  tags: unauth_kernels
...