---
- name: "4.1.1.1 Verify audit log storage size is configured (Not Scored)"
  vars:
    audit_conf: /etc/audit/auditd.conf
  block:
    - name: "4.1.1.1 Ensure audit log storage size is configured"
      lineinfile:
        path: "{{ audit_conf }}"
        regexp: "^[#\\s]*max_log_file\\s+=.*$"
        line: "max_log_file = 8"
        state: present
  tags:
    - cis
    - cis.4
    - cis.4.1
    - cis.4.1.1
    - cis.4.1.1.1
    - notscored
