---
- name: "4.1.5 Verify that events that modify date and time information are collected (Scored)"
  vars:
    audit_rules: /etc/audit/rules.d/audit.rules
  shell: |
      grep -q '^-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change$' {{ audit_rules }} && \
      grep -q '^-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change$' {{ audit_rules }} && \
      grep -q '^-a always,exit -F arch=b64 -S clock_settime -k time-change$' {{ audit_rules }} && \
      grep -q '^-a always,exit -F arch=b32 -S clock_settime -k time-change$' {{ audit_rules }} && \
      grep -q '^-w /etc/localtime -p wa -k time-change$' {{ audit_rules }}

  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.5
      - scored
