---
- name: "3.2.4 Verify if suspicious packets are logged (Scored)"
# Verifying the suspicious packet logging settings in /etc/sysctl.d/50-security-hardening.conf
  vars:
    security_hardening_conf: "/etc/sysctl.d/50-security-hardening.conf"
    net_ipv4_log_martians_expected: "net.ipv4.conf.all.log_martians=1"
    net_ipv4_default_log_martians_expected: "net.ipv4.conf.default.log_martians=1"
    net_ipv4_flush_expected: "net.ipv4.route.flush=1"
  block:
    - name: "3.2.4 verify if net.ipv4.conf.all.log_martians is set to 1"
      command: grep -Fxq {{ net_ipv4_log_martians_expected }} {{ security_hardening_conf }}
      register: output_1
    - fail:
        msg: "3.2.4 failed to verify if suspicious packets are logged, net.ipv4.conf.all.log_martians is not set to 1"
      when: output_1.rc != 0
    - name: "3.2.4 verify if net.ipv4.conf.default.log_martians is set to 1"
      command: grep -Fxq {{ net_ipv4_default_log_martians_expected }} {{ security_hardening_conf }}
      register: output_2
    - fail:
        msg: "3.2.4 failed to verify if suspicious packets are logged, net.ipv4.conf.default.log_martians is not set to 1"
      when: output_2.rc != 0
    - name: "3.2.4 verify if net.ipv4.route.flush is set to 1"
      command: grep -Fxq {{ net_ipv4_flush_expected }} {{ security_hardening_conf }}
      register: output_3
    - fail:
        msg: "3.2.4 failed to verify if suspicious packets are logged, net.ipv4.route.flush is not set to 1"
      when: output_3.rc != 0
  tags:
    - cis
    - cis.3
    - cis.3.2
    - cis.3.2.4
    - scored
