---
- name: "3.4.4 Verify permissions on /etc/hosts.allow are configured (Scored)"
  block:
    - name: "3.4.4 verify permissions"
      stat:
        path: /etc/hosts.allow
      register: etchosts_allow
    - fail:
        msg: "3.4.4 failed to verify uid. expected: 0. found: {{ etchosts_allow.stat.uid }}"
      when: etchosts_allow.stat.uid != 0
    - fail:
        msg: "3.4.4 failed to verify gid. expected: 0. found: {{ etchosts_allow.stat.gid }}"
      when: etchosts_allow.stat.gid != 0
    - fail:
        msg: "3.4.4 failed to verify permissions. expected: 0644. found: {{ etchosts_allow.stat.mode }}"
      when: etchosts_allow.stat.mode != "0644"
  tags:
    - cis
    - cis.3
    - cis.3.4
    - cis.3.4.4
    - scored

