---
- name: "3.5.2 Verify if SCTP is disabled (Not Scored)"
# Verifying the SCTP disablement settings in /etc/modprobe.d/modprobe.conf
  vars:
    modprobe_conf: "/etc/modprobe.d/modprobe.conf"
    sctp_settings_expected: "install sctp /bin/true"
  block:
    - name: 3.5.2 Verify if SCTP is disabled (Not Scored)
      lineinfile:
        name: "{{ modprobe_conf }}"
        line: "{{ sctp_settings_expected }}"
        state: present
      check_mode: yes
      register: presence
    - fail:
        msg: 3.5.2 failed to verify if SCTP is disabled, settings of SCTP is not expected in {{ modprobe_conf }}
      when: presence is changed
  tags:
    - cis
    - cis.3
    - cis.3.5
    - cis.3.5.2
    - notscored
